### PR TITLE
Fail unimplemented intrinsics instead of incorrect behavior

### LINKED ISSUE #99: Prefer not implementing intrinsics in a way that breaks in edge cases
For example `saturating_add` isn't implemented in a saturating way:

https://github.com/EmbarkStudios/rust-gpu/blob/f4f103197694290c469ad00d8f156ea7d0bfc292/rustc_codegen_spirv/src/builder/intrinsics.rs#L88-L97

This is more of a lesson I learnt the hard way than an issue with rust-gpu itself. While it may seem like a good idea at first to get it quickly working, it will backfire in the long term. I have spent quite a lot of time debugging miscompilations in cg_clif caused by exactly this kind of shortcuts. At minimum I think you should add a `FIXME` every time you add such a shortcut.

### PR DESCRIPTION
**Pull request by khyperia**
Fixes #99. Zombies are things in libcore, errors are things that aren't.

FYI @bjorn3

Also cleaned up some other minor stuff while in the area.

### CODE REVIEW

File: rustc_codegen_spirv/src/builder/builder_methods.rs [hunk 1]
```diff
@@ -568,6 +566,18 @@ impl<'a, 'tcx> BuilderMethods<'a, 'tcx> for Builder<'a, 'tcx> {
     simple_uni_op! {neg, s_negate}
     simple_uni_op! {fneg, f_negate}
 
+    fn exactudiv(&mut self, lhs: Self::Value, rhs: Self::Value) -> Self::Value {
+        let result = self.udiv(lhs, rhs);
+        self.zombie(result.def, "exactudiv is not supported yet");
```
Comment (bjorn3) [inline rustc_codegen_spirv/src/builder/builder_methods.rs:571]: You don't need a zombie here. `exactudiv` is the same as `udiv` except that it is UB when there is a remainder and in a few other cases. It is fine to just ignore the UB. You may want to add a FIXME to take advantage of the UB in the future.

Comment (khyperia) [reply rustc_codegen_spirv/src/builder/builder_methods.rs:571]: ah! neat :sparkles:

**Review by bjorn3 — APPROVED** [review]

**Review by Jasper-Bekkers — APPROVED** [review]

**Comment by khyperia** [comment]
@Mergifyio refresh
