### PR TITLE
Don't ICE on spir-v module version mismatch

### LINKED ISSUE #225: Better error message when SPIR-V version mismatch
Currently `rust-gpu` ICE's if you accidentally use a module with the wrong SPIR-V version. It would be better to provide a nice compiler error instead.
 
```
 thread 'rustc' panicked at 'assertion failed: `(left == right)`
    left: `(1, 0)`,
   right: `(1, 3)`', crates/rustc_codegen_spirv/src/linker/mod.rs:102:13
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

  error: internal compiler error: unexpected panic

  note: the compiler unexpectedly panicked. this is a bug.

  note: we would appreciate a bug report: https://github.com/EmbarkStudios/rust-gpu/issues/new

  note: rustc 1.49.0-nightly (25f6938da 2020-11-09) running on x86_64-apple-darwin
```

https://github.com/EmbarkStudios/rust-gpu/blob/9c8cec36396a1f328c8582da488d469963982590/crates/rustc_codegen_spirv/src/linker/mod.rs#L102

### PR DESCRIPTION
**Pull request by khyperia**
fixes #225

### CODE REVIEW

File: crates/rustc_codegen_spirv/src/linker/mod.rs [hunk 1]
```diff
@@ -99,7 +99,16 @@ pub fn link(sess: Option<&Session>, inputs: &mut [&mut Module], opts: &Options)
         for mut module in inputs.iter_mut().skip(1) {
             simple_passes::shift_ids(&mut module, bound);
             bound += module.header.as_ref().unwrap().bound - 1;
-            assert_eq!(version, module.header.as_ref().unwrap().version());
+            let this_version = module.header.as_ref().unwrap().version();
+            if version != this_version {
+                match sess {
+                    Some(sess) => sess.fatal(&format!(
+                        "cannot link two modules with different SPIR-V versions: v{}.{} and v{}.{}",
```
Comment (bjorn3) [inline crates/rustc_codegen_spirv/src/linker/mod.rs:106]: It would be nice to know the names of the modules.

**Review by XAMPPRocky — APPROVED** [review]
