### PR TITLE
Structurizer fixes

### LINKED ISSUE #193: Two breaks in a while loop cause error.
```rust
fn two_breaks(mut a: f32, mut b: f32) {
    let mut i = 0;
    while i < 10 {
        if a < 3.0 {
            break;
        }
        if b < 5.0 {
            break;
        }
        a += 1.0;
        b += 1.0;
        i += 1;
    }
}
```
```sh
Compiling wgpu-example-runner v0.1.0 (/home/dvc/implicit/marching_rays/runner)
error: failed to run custom build command for `wgpu-example-runner v0.1.0 (/home/dvc/implicit/marching_rays/runner)`

Caused by:
  process didn't exit successfully: `/home/dvc/implicit/marching_rays/target/debug/build/wgpu-example-runner-fbbe94bc606d1aa7/build-script-build` (exit code: 1)
  --- stderr
     Compiling wgpu-example-shader v0.1.0 (/home/dvc/implicit/marching_rays/shader)
  error: invalid cfg
    |
    = note: spirv-val failed
    = note: module "/home/dvc/implicit/marching_rays/target/spirv-unknown-unknown/release/deps/wgpu_example_shader.spv"

  error: aborting due to previous error

  error: could not compile `wgpu-example-shader`

  To learn more, run the command again with --verbose.
  Error: BuildFailed
```

### PR DESCRIPTION
**Pull request by VZout**
* The crappy modified id's fix would be unnecessary once I split "the analyzer" out of the structuration pass.
* Improved `get_possible_merge_positions` function. Still pretty bad but works better. I need to implement the proper algorithm at some point.
* Fixes #193 (`defer_loop_internals`)

Not using the `rspirv` builder. That will be one big PR replacing all the `new::Instruction` etc code.

### CODE REVIEW

File: crates/rustc_codegen_spirv/src/linker/structurizer.rs [hunk 1]
```diff
@@ -310,27 +522,34 @@ fn block_leads_into_continue(blocks: &[Block], cf_info: &ControlFlowInfo, start:
...
 }
 
-fn get_possible_merge_positions(
-    blocks: &[Block],
-    cf_info: &ControlFlowInfo,
-    start: Word,
-) -> Vec<usize> {
-    let mut retval = Vec::new();
+// every branch from a reaches b.
+fn block_is_reverse_idom_of(blocks: &[Block], cf_info: &ControlFlowInfo, a: Word, b: Word) -> bool {
```
Comment (khyperia) [inline crates/rustc_codegen_spirv/src/linker/structurizer.rs:526]: just checking, is this reverse idom or reverse dom? the comment and the function name are contradictory.

File: crates/rustc_codegen_spirv/src/linker/structurizer.rs [hunk 2]
```diff
@@ -341,20 +560,39 @@ fn get_possible_merge_positions(
...
+}
+fn get_possible_merge_positions(
+    blocks: &[Block],
+    cf_info: &ControlFlowInfo,
+    start: Word,
+) -> Vec<usize> {
+    let mut retval = Vec::new();
+    for (idx, block) in blocks.iter().enumerate() {
+        if block_is_reverse_idom_of(blocks, cf_info, start, block.label_id().unwrap()) {
+            retval.push(idx);
```
Comment (khyperia) [inline crates/rustc_codegen_spirv/src/linker/structurizer.rs:592]: this runtime pains me so much to see, but yeah, prototype phase, it's okay

File: crates/rustc_codegen_spirv/src/linker/structurizer.rs [hunk 3]
```diff
@@ -516,9 +761,16 @@ pub fn insert_selection_merge_on_conditional_branch(
         }
     }
 
+    let mut modified_ids = HashMap::new();
+
     // Find convergence point.
-    for id in branch_conditional_ops {
-        let bi = find_block_index_from_id(blocks, &id);
+    for id in branch_conditional_ops.iter() {
```
Comment (khyperia) [inline crates/rustc_codegen_spirv/src/linker/structurizer.rs:767]: `&branch_conditional_ops` instead of `branch_conditional_ops.iter()`?

File: crates/rustc_codegen_spirv/src/linker/structurizer.rs [hunk 4]
```diff
@@ -228,6 +229,217 @@ fn retarget_loop_children_if_needed(blocks: &mut [Block], cf_info: &ControlFlowI
...
+            incoming_edges.push(block.label_id().unwrap());
+        }
+    }
+
+    incoming_edges
+}
+
+fn num_incoming_edges(id: Word, blocks: &[Block]) -> usize {
+    incoming_edges(id, blocks).len()
+}
```
Comment (khyperia) [inline crates/rustc_codegen_spirv/src/linker/structurizer.rs:246]: it's fine it's a prototype aaa

File: crates/rustc_codegen_spirv/src/linker/structurizer.rs [hunk 5]
```diff
@@ -228,6 +229,217 @@ fn retarget_loop_children_if_needed(blocks: &mut [Block], cf_info: &ControlFlowI
...
+
+// detect the intermediate break block by checking whether a block that branches to a merge block has 2 parents.
+fn defer_loop_internals(
+    header: &mut ModuleHeader,
+    blocks: &mut Vec<Block>,
+    cf_info: &ControlFlowInfo,
+    debug_names: &mut Vec<(Word, String)>,
+    constants: &mut Vec<Instruction>,
+) {
+    for loop_info in &cf_info.loops {
```
Comment (khyperia) [inline crates/rustc_codegen_spirv/src/linker/structurizer.rs:329]: this is pretty far from what the final algorithm should be, but, it's fine for now

**Review by khyperia — APPROVED** [review]
Nice! Unfortunately I didn't really dig deep into the algorithms to verify things, I'm just trusting you. We should probably start adding a significant number of tests in this area (with some things to help out test speed, I have ideas)

File: crates/rustc_codegen_spirv/src/linker/structurizer.rs (hunk 4 above)
Comment (VZout) [reply crates/rustc_codegen_spirv/src/linker/structurizer.rs:246]: Ha should have removed that yeah

File: crates/rustc_codegen_spirv/src/linker/structurizer.rs (hunk 2 above)
Comment (VZout) [reply crates/rustc_codegen_spirv/src/linker/structurizer.rs:592]: you and me both

File: crates/rustc_codegen_spirv/src/linker/structurizer.rs (hunk 1 above)
Comment (VZout) [reply crates/rustc_codegen_spirv/src/linker/structurizer.rs:526]: Yep should be reverse dom. CFG names are hard.
