### PR TITLE
specializer: allow unused fully-constrained interface variables.

### LINKED ISSUE #723: Compiler panics when using #[spirv(object_to_world)]
Hi, I encountered compiler panic and I report here as output says.

### Expected Behaviour

The compiler doesn't panic.
I also want to know how do we use #[spirv(object_to_world)] correctly.

### Example & Steps To Reproduce

1. Create shader 

lib.rs

```rust 
#![cfg_attr(
    target_arch = "spirv",
    no_std,
    feature(register_attr),
    register_attr(spirv)
)]

use spirv_std::glam::Vec4;
#[cfg(not(target_arch = "spirv"))]
use spirv_std::macros::spirv;

#[spirv(closest_hit)]
pub fn test_closest_hit(#[spirv(object_to_world)] _object_to_world: [Vec4; 3]) {}

```
2. build it

build.rs

```rust
use std::error::Error;

use spirv_builder::{Capability, MetadataPrintout, SpirvBuilder};

fn main() -> Result<(), Box<dyn Error>> {
    SpirvBuilder::new("../shader", "spirv-unknown-vulkan1.2")
        .capability(Capability::RayTracingKHR)
        .extension("SPV_KHR_ray_tracing")
        .print_metadata(MetadataPrintout::Full)
        .build()?;

    Ok(())
}
```

3. get panic

```
> cargo build
    Blocking waiting for file lock on build directory
   Compiling builder v0.1.0 (C:\Users\hato2\Desktop\rust-gpu-issue\builder)
error: failed to run custom build command for `builder v0.1.0 (C:\Users\hato2\Desktop\rust-gpu-issue\builder)`

Caused by:
  process didn't exit successfully: `C:\Users\hato2\Desktop\rust-gpu-issue\target\debug\build\builder-8dcc5829546998ea\build-script-build` (exit code: 1)
  --- stderr
     Compiling core v0.0.0 (C:\Users\hato2\.rustup\toolchains\nightly-2021-08-10-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\core)
     Compiling rustc-std-workspace-core v1.99.0 (C:\Users\hato2\.rustup\toolchains\nightly-2021-08-10-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\rustc-std-workspace-core)
     Compiling compiler_builtins v0.1.49
     Compiling libm v0.2.1
     Compiling spirv-types v0.4.0-alpha.12
     Compiling bitflags v1.3.2
     Compiling num-traits v0.2.14
     Compiling glam v0.17.3
     Compiling spirv-std v0.4.0-alpha.12
     Compiling shader v0.1.0 (C:\Users\hato2\Desktop\rust-gpu-issue\shader)
  error: internal compiler error: unexpected panic

  note: the compiler unexpectedly panicked. this is a bug.

  note: we would appreciate a bug report: https://github.com/EmbarkStudios/rust-gpu/issues/new

  note: rustc 1.56.0-nightly (ae90dcf02 2021-08-09) running on x86_64-pc-windows-msvc

  note: compiler flags: -Z unstable-options -Z codegen-backend=C:\Users\hato2\Desktop\rust-gpu-issue\target\debug\rustc_codegen_spirv.dll -Z symbol-mangling-version=legacy -C opt-level=3 -C embed-bitcode=no -C target-feature=+RayTracingKHR,+ext:SPV_KHR_ray_tracing --crate-type lib --crate-type dylib

  note: some of the compiler flags provided by cargo are hidden

  query stack during panic:
  end of query stack
  note: `rust-gpu` version 0.4.0-alpha.12

  error: could not compile `shader`
  Error: BuildFailed
```

I created a repository for this issue https://github.com/hatoo/rust-gpu-issue.
You can reproduce by clone and build it.

## System Info

 - Rust: 1.56.0-nightly (ae90dcf02 2021-08-09)
 - OS: Windows 11 Pro
 - GPU: RTX 2080ti
 - SPIR-V: v2021.2-dev v2021.1-42-g5dd2f769

## Backtrace

<details><summary>Backtrace</summary>
<p>

```
<backtrace>
```

</p>
</details>

### PR DESCRIPTION
**Pull request by eddyb**
Fixes #723.

For a bit of background, this is what happens for e.g. an `Input` interface variable `x: f32`, during inference/specialization of `OpTypePointer` by storage class:
```
%f32_ptr<SC0: StorageClass> = OpTypePointer SC0 %f32
```
```
%x<SC0: StorageClass>: %f32_ptr<SC0> = OpVariable Input
    where SC0 = Input
```
```
OpEntryPoint ... %x
```

We're in a weird situation, where `%x` is fully determined to always be `%x<Input>`, because of the typing rule of `OpVariable S: (OpTypePointer S _)` (i.e. the redundancy of the storage class), *but* it still started out as "generic", and its type is an application of a "generic", so we have to treat it as such for consistency.

This isn't normally a problem, as any use of `%x` will be forced to instantiate `%x<Input>`, and so the `OpEntryPoint` will rely on that instance to replace its use of `%x` with `%x<Input>`.

However, if `%x` happens to be unused in the actual entry-point *function*, we would've panicked, before this PR, as the `OpEntryPoint` couldn't use any existing instances.

This PR works around that by "simply" instantiating any interface variables listed in `OpEntryPoint`, that have all of their "storage class parameters" fully constrained to concrete storage classes (and therefore require no inference/specialization).

### CODE REVIEW

File: tests/ui/dis/issue-723.rs [hunk 1]
```diff
@@ -0,0 +1,11 @@
...
+// compile-flags: -Ctarget-feature=+RayTracingKHR,+ext:SPV_KHR_ray_tracing
+// compile-flags: -C llvm-args=--disassemble-globals
+// normalize-stderr-test "OpCapability VulkanMemoryModel\n" -> ""
+// normalize-stderr-test "OpExtension .SPV_KHR_vulkan_memory_model.\n" -> ""
+// normalize-stderr-test "OpMemoryModel Logical Vulkan" -> "OpMemoryModel Logical Simple"
+
+use spirv_std as _;
+
+#[spirv(closest_hit)]
+pub fn test_closest_hit(#[spirv(object_to_world)] _object_to_world: [glam::Vec4; 3]) {}
```
Comment (khyperia) [inline tests/ui/dis/issue-723.rs:11]: Probably want to use a slightly modified test case, `object_to_world` requires an OpTypeMatrix on vulkan and so it's going to give an error when compiletest has target env of vulkan.

**Review by khyperia — APPROVED** [review]

File: tests/ui/dis/issue-723.rs (hunk 1 above)
Comment (eddyb) [reply tests/ui/dis/issue-723.rs:11]: Ah huh I haven't been running `cargo compiletest` with any flags lately because U thought Vulkan was the default.

**Review by hatoo — APPROVED** [review]

File: tests/ui/dis/issue-723.rs (hunk 1 above)
[the remark this answers is not in the document]
Comment (eddyb) [reply tests/ui/dis/issue-723.rs]: I'm not using that test anymore, because of https://github.com/EmbarkStudios/rust-gpu/pull/729#discussion_r691831516, anyway.
